[package]
name = "numa_alloc_rs"
version = "0.1.0"
edition = "2024"

[features]
# Use the unstable `allocator_api` from `std` instead of the `allocator-api2` mirror
nightly = []

[dependencies]
allocator-api2 = { version = "0.4.0", default-features = false }
thiserror = "2.0.20"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.189"
